### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by oakniiv** [Keidan/SlideshowWallpaper#1]
Would you be able to make an app that changes the wallpaper on double tap (My Wallpaper Slideshow on the Store already has that feature), also could you make it so we can also set videos as wallpaper and have it loop until changed by double tap?

**Comment by Keidan** [comment]
Hello, sorry for the late reply.

* Point 1 is possible.
* Point 2 requires an animated wallpaper, but I don't think that the video format is supported, but this kind of feature may drain the battery.

On the other hand, to answer the subject of the issue, indeed this project is no longer active.
